name: real_estate
dependencies:
  - python=3.9
  - pip=21.1.3
  - pip:
    - flask==2.0.1
    - jupyterlab==3.1.10
    - loguru==0.5.3
    - matplotlib==3.4.3
    - numpy==1.21.2
    - pandas==1.3.0
    - pre-commit==2.13.0
    - scikit-learn==0.24.2
    - seaborn==0.11.2
